<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/01_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

#Podstawowe struktury danych: pd.Series

In [2]:
s = pd.Series(data=[1,2,4,6])
s

0    1
1    2
2    4
3    6
dtype: int64

indeks można dowolnie zmienić

za indeks można użyć daty!

In [5]:
s = pd.Series(data=[1.,2,4,6], index=['a','b','c','d'], name ='sample') #jeden float, wszędzie float
s

a    1.0
b    2.0
c    4.0
d    6.0
Name: sample, dtype: float64

wstawianie braków danych

In [6]:
import numpy as np
np.nan

nan

brak wartości - wartość NaN nie zostanie wzięta pod uwagę przy wyliczeniach - w przeciwieństwie do np. wartości 0

In [7]:
s = pd.Series(data=[1.,np.nan,4,6], index=['a','b','c','d'], name ='sample') #jeden float, wszędzie float
s

a    1.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [8]:
s = pd.Series(data=[True,False,False])
s

0     True
1    False
2    False
dtype: bool

In [13]:
s = pd.Series(data=np.arange(10,20), index=pd.date_range(start='20200101',periods=10)) #period - ile dni od dnia startu
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64