<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/03_wizualizacje_danych/06_plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Plotly

In [2]:
import plotly
import plotly.graph_objects as go
plotly.__version__

'5.24.1'

##Wykres słupkowy

In [6]:
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3, 4])], #jeden element "normalnie", więcej - jako listę
    #layout_title_text="A Figure Displayed with fig.show()"
)
fig.show()

In [10]:
fig = go.Figure(
    data=go.Bar(y=[2, 1, 3, 4]),
    layout=go.Layout(title={'text': 'Wykres słupkowy'})
    )
fig.show()

In [12]:
fig = go.Figure(
    data=go.Bar(y=[2, 1, 3, 4]),
    layout=go.Layout(title_text='Wykres słupkowy')
    )
#zapis do pliku html - można pobrać i z nim pracować
fig.write_html('bar.html')
fig.show()

##Wykres kołowy i pierścieniowy -Diamonds

In [13]:
from seaborn import load_dataset
df = load_dataset('diamonds')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

In [19]:
dff = df.cut.value_counts()
dff = dff.reset_index()
dff.columns = ['type', 'count']
dff

        type  count
0      Ideal  21551
1    Premium  13791
2  Very Good  12082
3       Good   4906
4       Fair   1610

In [23]:
fig = go.Figure(
    data=go.Pie(labels=dff['type'], values=dff['count']),
    layout=go.Layout(title={'text': 'Rozkład zmiennej cut'}, width=800)
)
fig.show()

In [24]:
#wykres pierścieniowy - z parametrem hole
fig = go.Figure(
    data=go.Pie(labels=dff['type'], values=dff['count'], hole = 0.5),
    layout=go.Layout(title={'text': 'Rozkład zmiennej cut'}, width=800)
)
fig.show()

##Diagram Sankey'a

np. przepływ klientów

In [25]:
data = [go.Sankey(node=dict(label=['Nonchurn_2018', 'Churn_2018', 'Nonchurn_2019', 'Churn_2019']),
                 link=dict(source=[0, 0, 1, 1], # indeks odpowiadający etykiecie (labels)
                          target=[2, 3, 2, 3],
                          value=[65, 12, 18, 5]))] #wartość przepuszczana od źródła do celu

fig = go.Figure(data=data, layout=go.Layout(width=800, height=400))
fig.show()
#można przesuwać po wyświetleniu

In [26]:
data = [go.Sankey(node=dict(label=['Nonchurn_2018', 'Churn_2018', 'Nonchurn_2019',
                                   'Churn_2019', 'Nonchurn_2020', 'Churn_2020']),
                 link=dict(source=[0, 0, 1, 1, 2, 3], # indeks odpowiadający etykiecie (labels)
                          target=[2, 3, 2, 3, 4, 5],
                          value=[65, 10, 5, 20, 70, 30]))]

fig = go.Figure(data=data, layout=go.Layout(width=800, height=400))
fig.show()

In [27]:
data = [go.Sankey(node=dict(label=['Nonchurn_2018', 'Churn_2018', 'Nonchurn_2019',
                                   'Churn_2019', 'Nonchurn_2020', 'Churn_2020']),
                 link=dict(source=[0, 0, 1, 1, 2, 2, 3, 3], # indeks odpowiadający etykiecie (labels)
                          target=[2, 3, 2, 3, 4, 5, 4, 5],
                          value=[65, 10, 5, 20, 60, 10, 15, 15]))]

fig = go.Figure(data=data, layout=go.Layout(width=800, height=400))
fig.show()

##Wykres świecowy

In [29]:
def fetch_financial_data(company='AMZN'):
    """
    This function fetch stock market quotations.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

df = fetch_financial_data()
df = df.reset_index()
df = df[df.Date > '2026-01-01']
df.head(3)

        Date     Open     High      Low   Close    Volume
0 2026-03-17  212.820  215.700  212.430  215.20  44969943
1 2026-03-16  208.350  212.724  207.445  211.74  42209316
2 2026-03-13  209.605  210.560  206.220  207.67  35662137

In [30]:
fig = go.Figure(data=go.Candlestick(x=df.Date, open=df.Open, high=df.High, low=df.Low, close=df.Close))
fig.show()